### ISSUE TITLE
How can I configure a TDNN network of kaldi to tfkaldi?

### ISSUE THREAD

**Issue by xinq2016** [vrenkens/tfkaldi#3]
Hi vrenkens,

   I wanna know how can I configure a TDNN network with ivector in tfkaldi?
 
  for example, 
steps/nnet3/train_tdnn.sh --stage $train_stage \
    --num-epochs 8 --num-jobs-initial 2 --num-jobs-final 14 \
    --splice-indexes "-4,-3,-2,-1,0,1,2,3,4  0  -2,2  0  -4,4 0" \
    --feat-type raw \
    --online-ivector-dir exp/nnet3/ivectors_train_si284 \
    --cmvn-opts "--norm-means=false --norm-vars=false" \
    --initial-effective-lrate 0.005 --final-effective-lrate 0.0005 \
    --cmd "$decode_cmd" \
    --pnorm-input-dim 2000 \
    --pnorm-output-dim 250 \
    data/train_si284_hires data/lang exp/tri4b_ali_si284 $dir  || exit 1;

**Comment by vrenkens** [comment]
Hi,

A TDNN is not implemented in tfkaldi, you could always implement the 
network yourself. We are not planning to implement a TDNN because we are 
going to use RNNs for sequence modeling.
If you want to check out the progress on that you can check out the CTC 
branch.

Cheers,
Vincent
