### ISSUE TITLE
utt splice bug

### ISSUE THREAD

**Issue by GaofengCheng** [vrenkens/tfkaldi#6]
@vrenkens 
I'm afraid your fix still exits some bug.
below is your fix:
```
        #read utterance
        (utt_id, utt_mat, looped) = self.reader.read_next_utt()

        #apply cmvn
        cmvn_stats = self.reader_cmvn.read_utt(self.utt2spk[utt_id])
        utt_mat = apply_cmvn(utt_mat, cmvn_stats)

        #splice the utterance
        utt_mat = splice(utt_mat, self.context_width)

        return utt_id, utt_mat, looped
```
problem is that : too short utt have lable, skip utt_mat,will return` utt_id,None,looped`
here means a utt_id without mat will exit in training, I'm afraid this will cause problem.
Why I use `splice_control` is to skip that utt(both mat and id), if it's too short, read next utt, but not return a utt with None utt_mat and not None utt_id

**Comment by GaofengCheng** [comment]
@vrenkens I have tested `splice_control ` method  , it does solve the crash

**Comment by vrenkens** [comment]
Hi Gaofeng,

This code you posted is not the only fix I'm checking if the utt_mat is None in the batchdispenser. If it is it will not be added to the batch. 

Vincent

**Comment by GaofengCheng** [comment]
@vrenkens en... I just noticed it, thanks for fixing :+1:
