### ISSUE TITLE
Can't see the doc page

### ISSUE THREAD

**Issue by jinpoon** [vrenkens/tfkaldi#8]
Hi, it seems that the url of the document page in http://vrenkens.github.io/tfkaldi/ is linked to the github.io page itself. Or did I get anything wrong? Thank you!

**Comment by Some-random** [comment]
I'm having this issue too. Can someone post a link to the real doc for me please?

**Comment by vrenkens** [comment]
That's normal. You can look at a list of classes and files with documentation using the corresponding menus on the top of the page
